### ISSUE TITLE
Error when calling ".can(role)"

### ISSUE THREAD

**Issue by riveraser** [onury/accesscontrol#13]
This is what I am getting:

```
//Printing permissions

console.log(ac.getGrants());
```
-------
```
{ ADMIN: 
   { customers: 
      { 'create:any': [Object],
        'delete:any': [Object],
        'read:any': [Object] }
      }
}
```
---------

But when I do

`  var permission = ac.can(userRole).readAny('customers');`

I am getting this error: (userRole is ADMIN)

Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property '$extend' of undefined
    at /apps/node-apps/figgojs-live/node_modules/accesscontrol/lib/utils.js:58:35
    at Array.forEach (native)
    at Object.getFlatRoles (/apps/node-apps/figgojs-live/node_modules/accesscontrol/lib/utils.js:56:15)
    at Object.getUnionAttrsOfRoles (/apps/node-apps/figgojs-live/node_modules/accesscontrol/lib/utils.js:224:27)
    at new Permission (/apps/node-apps/figgojs-live/node_modules/accesscontrol/lib/core/Permission.js:52:45)
    at Query._getPermission (/apps/node-apps/figgojs-live/node_modules/accesscontrol/lib/core/Query.js:266:16)
    at Query.readAny (/apps/node-apps/figgojs-live/node_modules/accesscontrol/lib/core/Query.js:152:21)
    at /apps/node-apps/figgojs-live/Routes/AdminRoute.js:100:41
    at /apps/node-apps/figgojs-live/Utils/UniversalFunctions.js:589:13
    at /apps/node-apps/figgojs-live/node_modules/jsonwebtoken/index.js:155:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by onury** [comment]
When I test `var permission = ac.can('ADMIN').readAny('customers');`, this works with the grants you've given. See [this test on runkit](http://runkit.com/onury/accesscontrol-issue-13).

Are you sure your variable `userRole` is actually set to `"ADMIN"`? Can you do `console.log(userRole)` right before the line where you check for permission and see?

It seems you're calling for a non-existing role.

**Comment by riveraser** [comment]
Hi, thanks for the fast reply and you are right, I had a TYPO in  "userRole" var :-(

**Comment by onury** [comment]
no worries.

**Comment by onury** [comment]
Actually this should throw with a message indicating that the role is not found. Will be in the next release.
